set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_ENV_PASSTHROUGH PATH)
SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)

set(VCPKG_CMAKE_SYSTEM_NAME LLVM_MinGW)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "F:/repos/vcpkg/scripts/toolchains/llvm-mingw.cmake")
set(CMAKE_PREFIX_PATH "F:/git-sdk-64/usr/src/llvm-build")
